spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  api-docs:
    path: /doc/swagger/json
    enabled: true
  swagger-ui:
    path: /doc/index.html
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect