spring:
  application:
    name: ms_flies
  datasource:
    url: jdbc:mysql://localhost:3306/Aerolinea_EveryoneFiles
    username: root
    password: 026ba91D..
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: never