-- -----------------------------------------------------
-- Schema dbProyecto_EveryOneFlies
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS dbProyecto_EveryOneFlies;

-- -----------------------------------------------------
-- Table `AEROLINEA`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS AEROLINEA (
    ID_AEROLINEA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(15) NOT NULL,
    SIGLAS VARCHAR(3) NOT NULL
);

-- -----------------------------------------------------
-- Table `LOCATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS LOCATION (
    ID_LOCATION INT PRIMARY KEY AUTO_INCREMENT,
    PAIS VARCHAR(15) NULL,
    CIUDAD VARCHAR(15) NULL,
    FECHA_INICIO_ALTA DATE NULL,
    FECHA_FIN_ALTA DATE NULL,
    FECHA_INICIO_ALTA_DOS DATE NULL,
    FECHA_FIN_ALTA_DOS DATE NULL,
    FECHA_INICIO_MEDIA DATE NULL,
    FECHA_FIN_MEDIA DATE NULL,
    FECHA_INICIO_MEDIA_DOS DATE NULL,
    FECHA_FIN_MEDIA_DOS DATE NULL,
    PRECIO_BASE DOUBLE NULL
);

-- -----------------------------------------------------
-- Table `AEROPUERTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS AEROPUERTO (
  ID_AEROPUERTO INT PRIMARY KEY AUTO_INCREMENT,
  CODIGO_IATA VARCHAR(3) NOT NULL,
  NOMBRE_AEROPUERTO VARCHAR(50) NOT NULL,
  ID_LOCATION INT NOT NULL,
  FOREIGN KEY (ID_LOCATION)
    REFERENCES LOCATION(ID_LOCATION)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- -----------------------------------------------------
-- Table `VUELO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS VUELO (
    ID_VUELO BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODIGO VARCHAR(255),
    ID_AEROLINEA INT NOT NULL,
    ID_AEROPUERTO_ORIGEN INT NOT NULL,
    ID_AEROPUERTO_DESTINO INT NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    HORA_SALIDA TIME NOT NULL,
    FECHA_LLEGADA DATE NOT NULL,
    HORA_LLEGADA TIME NOT NULL,
    ECONOMICOS INT NOT NULL,
    ECONOMICOS_PREMIUN INT NOT NULL,
    BUSINESS INT NOT NULL,
    PRIMERA_CLASE INT NOT NULL,
    TOTAL_PUESTOS INT NOT NULL,

    CONSTRAINT FK_AEROLINEA FOREIGN KEY (ID_AEROLINEA)
            REFERENCES AEROLINEA(ID_AEROLINEA),

    CONSTRAINT FK_AEROPUERTO_ORIGEN FOREIGN KEY (ID_AEROPUERTO_ORIGEN)
        REFERENCES AEROPUERTO(ID_AEROPUERTO),

    CONSTRAINT FK_AEROPUERTO_DESTINO FOREIGN KEY (ID_AEROPUERTO_DESTINO)
        REFERENCES AEROPUERTO(ID_AEROPUERTO)
);

-- -----------------------------------------------------
-- Table `ASIENTO`
-- -----------------------------------------------------
CREATE TABLE ASIENTOS (
    ID_ASIENTO INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_ASIENTO VARCHAR(255),
    ID_VUELO BIGINT NOT NULL,
    DISPONIBLE BOOLEAN NOT NULL,
    TIPO_ASIENTO VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_VUELO) REFERENCES VUELO(ID_VUELO)
);
